Update the update-bootloader script.

diff --git a/update-bootloader b/update-bootloader
--- a/update-bootloader
+++ b/update-bootloader
@@ -1,9 +1,5 @@
 #!/bin/bash
 
-echo 'Not yet updated to work with Mint 19 - do not use'
-exit 1
-
-
 SETTINGS_DIR="${HOME}/.mint-encrypted-install"
 
 function load-setting() {
@@ -12,8 +8,7 @@ function load-setting() {
 }
 
 function save-setting() {
-    # shellcheck disable=SC2015
-    mkdir -p "${SETTINGS_DIR}" &&
+    mkdir -p "${SETTINGS_DIR}" && # shellcheck: disable=SC2015
     echo "${2}" > "${SETTINGS_DIR}/${1}" || fail
 }
 
@@ -63,9 +58,8 @@ function fail() {
 
 
 cat <<EOF
-This script will update the initramfs and bootloader, from inside a
-running Mint installation previously set up using
-mint-encrypted-install.
+This script will update the initramfs and bootloader, from inside a running
+Mint installation previously set up using mint-encrypted-install.
 EOF
 
 if ! yn-n "Continue?"; then
@@ -74,13 +68,18 @@ fi
 
 
 # Not completely foolproof, but should do the job...
-if ! lsb_release -a 2>/dev/null | grep 'sarah\|serena\|sonya\|sylvia' &>/dev/null || type ubiquity &>/dev/null; then
+if ! lsb_release -a 2>/dev/null | grep 'tara\|tessa' &>/dev/null || type ubiquity &>/dev/null; then
 cat <<EOF
 
 
-You are not running on an installed Linux Mint 18, 18.1, 18.2 or 18.3
-system. Cannot go any further.
+You are not running on an installed Linux Mint 19 or 19.1 system. Cannot go any
+further.
 EOF
+    exit 1
+fi
+
+if [ ! -e '/sys/firmware/efi' ]; then
+    echo 'Your firmware is BIOS. This script only supports UEFI. Cannot go any further.'
     exit 1
 fi
 
@@ -90,20 +89,9 @@ sudo true || fail
 echo
 
 
-if [ -e '/sys/firmware/efi' ]; then
-    FIRMWARE='uefi'
-else
-    FIRMWARE='bios'
-fi
-
-
 # Load settings
 BOOT_DEVICE="$(load-setting boot-device)"
-
-if [ "${FIRMWARE}" = 'uefi' ]; then
-    UEFI_PARTITION_NUM="$(load-setting uefi-partition-num)"
-    UEFI_BOOT_ENTRY="$(load-setting uefi-boot-entry)"
-fi
+UEFI_PARTITION_NUM="$(load-setting uefi-partition-num)"
 
 
 # Check settings
@@ -121,34 +109,14 @@ EOF
     echo
 fi
 
-if [ "${FIRMWARE}" = 'uefi' ]; then
-     if [ ! -z "${UEFI_PARTITION_NUM}" ]; then
-         cat <<EOF
+if [ ! -z "${UEFI_PARTITION_NUM}" ]; then
+    cat <<EOF
     UEFI partition number on boot device: ${UEFI_PARTITION_NUM}
 EOF
-         if ! yn-y '    Is this correct?'; then
-             UEFI_PARTITION_NUM=''
-         fi
-         echo
-     fi
-
-     if [ ! -z "${UEFI_BOOT_ENTRY}" ]; then
-         cat <<EOF
-Valid options for UEFI boot entry are any of the four-digit hex
-numbers listed below:
-
-EOF
-         sudo efibootmgr
-         echo
-         cat <<EOF
-    UEFI boot entry: ${UEFI_BOOT_ENTRY}
-
-EOF
-         if ! yn-n '    Is this correct?'; then
-             UEFI_BOOT_ENTRY=''
-         fi
-         echo
-     fi
+    if ! yn-y '    Is this correct?'; then
+        UEFI_PARTITION_NUM=''
+    fi
+    echo
 fi
 
 
@@ -165,63 +133,28 @@ if [ -z "${BOOT_DEVICE}" ]; then
     echo
 fi
 
-if [ "${FIRMWARE}" = 'uefi' ]; then
+if [ -z "${UEFI_PARTITION_NUM}" ]; then
+    echo 'Block devices:'
+    lsblk
+    echo
+    read -r -p "Enter the number of the UEFI boot partition, e.g. if the partition is /dev/sda1 on a hard drive, enter 1, or /dev/nvme0n1p2 on an NVME SSD, enter 2: " UEFI_PARTITION_NUM || fail
     if [ -z "${UEFI_PARTITION_NUM}" ]; then
-        echo 'Block devices:'
-        lsblk
-        echo
-        read -r -p "Enter the number of the UEFI boot partition, e.g. if the partition is /dev/sda1 on a hard drive, enter 1, or /dev/nvme0n1p2 on an NVME SSD, enter 2: " UEFI_PARTITION_NUM || fail
-        if [ -z "${UEFI_PARTITION_NUM}" ]; then
-            echo 'Invalid partition number'
-            fail
-        fi
-        save-setting uefi-partition-num "${UEFI_PARTITION_NUM}"
-        echo
+        echo 'Invalid partition number'
+        fail
     fi
-
-    if [ -z "${UEFI_BOOT_ENTRY}" ]; then
-        echo "Existing boot entries are:"
-        echo
-        sudo efibootmgr
-        echo
-        read -r -p "Enter the four-digit hex number of an existing boot entry to update it, or leave this blank to create a new one: " UEFI_BOOT_ENTRY || fail
-        save-setting uefi-boot-entry "${UEFI_BOOT_ENTRY}"
-        echo
-    fi
+    save-setting uefi-partition-num "${UEFI_PARTITION_NUM}"
+    echo
 fi
 
 
 # Now actually start the update
 sudo locale-gen --purge --no-archive &&
-# shellcheck disable=SC2015
-sudo update-initramfs -u || fail
+sudo update-initramfs -u &&
+sudo update-grub && # shellcheck: disable=SC2015
+sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Mint --boot-directory=/boot --modules="all_video boot btrfs cat chain configfile crypto cryptodisk disk diskfilter echo efifwsetup efinet ext2 fat font gettext gcry_arcfour gcry_blowfish gcry_camellia gcry_cast5 gcry_crc gcry_des gcry_dsa gcry_idea gcry_md4 gcry_md5 gcry_rfc2268 gcry_rijndael gcry_rmd160 gcry_rsa gcry_seed gcry_serpent gcry_sha1 gcry_sha256 gcry_sha512 gcry_tiger gcry_twofish gcry_whirlpool gfxmenu gfxterm gfxterm_background gzio halt hfsplus iso9660 jpeg keystatus loadenv loopback linux linuxefi lsefi lsefimmap lsefisystab lssal luks lvm mdraid09 mdraid1x memdisk minicmd normal part_apple part_msdos part_gpt password_pbkdf2 png raid5rec raid6rec reboot search search_fs_uuid search_fs_file search_label sleep squash4 test true verify video zfs zfscrypt zfsinfo" --recheck || fail
 
-
-if [ "${FIRMWARE}" = 'bios' ]; then
-    sudo update-grub &&
-    sudo grub-mkconfig -o /boot/grub/grub.cfg &&
-    # shellcheck disable=SC2015
-    sudo grub-install "${BOOT_DEVICE}" || fail
-elif [ "${FIRMWARE}" = 'uefi' ]; then
-    sudo update-grub &&
-    sudo mkdir -p /boot/efi/EFI/mint &&
-    sudo grub-mkconfig -o /boot/efi/EFI/mint/grub.cfg &&
-    echo "configfile \${cmdpath}/grub.cfg" | sudo tee /tmp/grub.cfg &>/dev/null &&
-    # shellcheck disable=SC2015
-    sudo grub-mkstandalone -d /usr/lib/grub/x86_64-efi/ -O x86_64-efi --compress="xz" --modules="part_gpt part_msdos crypto cryptodisk luks disk diskfilter lvm" --fonts="unicode" -o "/boot/efi/EFI/mint/grubx64.efi"  "boot/grub/grub.cfg=/tmp/grub.cfg" -v || fail
-
-    echo
-    if [ -z "${UEFI_BOOT_ENTRY}" ]; then
-        # Create a new boot entry
-        sudo efibootmgr -c -d "${BOOT_DEVICE}" -p "${UEFI_PARTITION_NUM}" -L "Mint" -l "\EFI\mint\grubx64.efi" || fail
-    else
-        # Update an existing boot entry
-        sudo efibootmgr -b "${UEFI_BOOT_ENTRY}" -d "${BOOT_DEVICE}" -p "${UEFI_PARTITION_NUM}" -L "Mint" -l "\EFI\mint\grubx64.efi" || fail
-    fi
-else
-    # Should never get here
-    fail
-fi
+# Print out the boot order
+sudo efibootmgr
 
 cat <<EOF
 
